steps:
- name: golang:1.21
  id: Test
  endpoint: /bin/bash
  args:
  - "-c"
  - |
    go test -v ./...
  
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - '${_ARTIFACT_REGISTRY_URL}:$SHORT_SHA'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - '${_ARTIFACT_REGISTRY_URL}:$SHORT_SHA'

substitutions:
  _ARTIFACT_REGISTRY_URL: asia-southeast2-docker.pkg.dev/dev-devsecops-exp/khhini-dev/sample-app