version: '3.3'
services:
  sample-app:
    image: asia-southeast2-docker.pkg.dev/dev-devsecops-exp/khhini-dev/sample-app:v1.0
    build: 
      context: ../../
      dockerfile: deployments/docker/Dockerfile
    container_name: sample-app
    ports:
      - 9000:8080
